### ISSUE TITLE
Add the checking before API call to WP Repository

### ISSUE THREAD

**Issue by alexxgermann** [parallelus/Plugin-Installer-for-Runway#19] opened 2016-06-14 10:07 UTC
Add the checking and if plugin is installed - do not execute the request.

**Comment by alexxgermann** [comment] 2016-06-14 13:12
@jeffwalker99 Could you please test these changes?

**Comment by jeffwalker99** [comment] 2016-06-14 13:25
Okay.

**Comment by jeffwalker99** [comment] 2016-06-14 13:36
On a fresh install it installed and activated all the plugins, but after activation the WP repo plugins (Ninja Forms and Sidekick) are flagged as having updates available when they don't...

![2016-06-14_14-34-20](https://cloud.githubusercontent.com/assets/4571369/16044674/5527de52-323d-11e6-8cb7-b3299f909075.png)

**Comment by jeffwalker99** [comment] 2016-06-27 08:35
@alexxgermann 

When testing this I'm still getting the same problem as described in my previous post.

**Comment by jeffwalker99** [comment] 2016-06-27 08:39
Ah. When I revert to the distribution version of GoExplore! the problem is also still there, so it looks like the problem is in the database?

**Comment by jeffwalker99** [comment] 2016-06-27 08:51
Okay, I've tested again wth a fresh install of GoExplore! and the problem is fixed.

I also tested with updating the distribution version with the latest plugin installer and the problem is also fixed.

So I think we can close this issue now. :)

**Closed by jeffwalker99** 2016-06-27 08:51 UTC
Labels: enhancement, fixed
